#!/bin/sh

mkdir FilesForPlotting_207/

cp Fangorn_GTDB_207/Outputs_Complete/master_rrna.gff FilesForPlotting_207/gtdb_complete_master_rrna.gff
cp Fangorn_GTDB_207/Outputs_Incomplete/master_rrna.gff FilesForPlotting_207/gtdb_incomplete_master_rrna.gff
cp Fangorn_RefSeq_207/Outputs_Complete/master_rrna.gff FilesForPlotting_207/refseq_complete_master_rrna.gff
cp Fangorn_RefSeq_207/Outputs_Incomplete/master_rrna.gff FilesForPlotting_207/refseq_incomplete_master_rrna.gff

cp Fangorn_GTDB_207/Outputs_Combined/vsearch_centroids.tsv FilesForPlotting_207/gtdb_combined_vsearch_centroids.tsv
cp Fangorn_GTDB_207/Outputs_Combined/vsearch_hits.tsv FilesForPlotting_207/gtdb_combined_vsearch_hits.tsv
cp Fangorn_RefSeq_207/Outputs_Combined/vsearch_centroids.tsv FilesForPlotting_207/refseq_combined_vsearch_centroids.tsv
cp Fangorn_RefSeq_207/Outputs_Combined/vsearch_hits.tsv FilesForPlotting_207/refseq_combined_vsearch_hits.tsv

cp Fangorn_GTDB_207/gtdb_taxonomy.tsv FilesForPlotting_207/gtdb_assemblytaxonomy.tsv
cp Fangorn_RefSeq_207/assemblyaccession_taxid_lineage_mpa.txt FilesForPlotting_207/refseq_assemblytaxonomy.tsv

cp Fangorn_GTDB_207/Outputs_Complete/taxRep.tsv FilesForPlotting_207/gtdb_complete_taxRep.tsv
cp Database_GTDB_207/NR/taxRep.tsv FilesForPlotting_207/gtdb_combined_taxRep.tsv
cp Fangorn_GTDB_207/Outputs_Combined/taxCombined.tsv FilesForPlotting_207/gtdb_taxCombined.tsv
cp Fangorn_RefSeq_207/Outputs_Complete/taxRep.tsv FilesForPlotting_207/refseq_complete_taxRep.tsv
cp Database_RefSeq_207/NR/taxRep.tsv FilesForPlotting_207/refseq_combined_taxRep.tsv
cp Fangorn_RefSeq_207/Outputs_Combined/taxCombined.tsv FilesForPlotting_207/refseq_taxCombined.tsv

cp Fangorn_GTDB_207/Outputs_Complete/operons_unlinked_or_crossingboundary.tsv FilesForPlotting_207/gtdb_complete_unlinkedorcrossingboundary.tsv
cp Fangorn_GTDB_207/Outputs_Incomplete/operons_unlinked_or_crossingboundary.tsv FilesForPlotting_207/gtdb_incomplete_unlinkedorcrossingboundary.tsv
cp Fangorn_RefSeq_207/Outputs_Complete/operons_unlinked_or_crossingboundary.tsv FilesForPlotting_207/refseq_complete_unlinkedorcrossingboundary.tsv
cp Fangorn_RefSeq_207/Outputs_Incomplete/operons_unlinked_or_crossingboundary.tsv FilesForPlotting_207/refseq_incomplete_unlinkedorcrossingboundary.tsv
